### PR TITLE
Add IE 10 and 11 browser support & Screenshot!

### PR DESCRIPTION
**Pull request by IamManchanda**
Oh this PR will be in [my] history books!!!

### CODE REVIEW

**Comment by IamManchanda** [comment]
cc @kball for the **HOLY** merge!

**Comment by kball** [comment]
@IamManchanda can you add a variable that verifies if to include the IE specific or not? It's a lot of bloat, would like to allow folks to disable

**Comment by IamManchanda** [comment]
Sure @kball ? 

> It's a lot of bloat
This bloat will only work for IE!

**Comment by IamManchanda** [comment]
DONE @kball 

YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES

---

So excited!!!

**Pull request merged**
